// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewrcaocedacakfxfynkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cmNhb2NlZGFjYWtmeGZ5bmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTU5NDEsImV4cCI6MjA2OTM3MTk0MX0.eb9nYidhUQ78vDgBIB9RywkU7ptvjcH1C03RMIiDqjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});